In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
from tqdm import tqdm

save_dir = Path("/nas/cee-water/cjgleason/ted/swot-ml/data/multigraph_manual")
metadata_dir = save_dir / "metadata"

gauges = gpd.read_parquet(metadata_dir / "gauges.parquet").set_index('site_id')

subs_df = pd.read_parquet(metadata_dir / 'subbasins.parquet', columns=['site_id', 'is_gauge', 'uparea_km2', 'outlet_id'])
subs_df.index = subs_df.index.astype(str)

basin_subbasin_dict = subs_df.groupby('outlet_id').apply(lambda g: g.index.tolist(), include_groups=False).to_dict()

In [2]:
from data import ZarrBasinStore
store_path = Path("/scratch4/workspace/tlanghorst_umass_edu-zbs_vD")
store = ZarrBasinStore(store_path)

In [ ]:
store.compute_and_store_stats()

Dask client started. Dashboard at: http://127.0.0.1:8787/status

Basins:  32%|███▏      | 464/1473 [00:23<00:50, 19.98it/s]

In [3]:
from data import BasinDataLake

datalake = BasinDataLake('/nas/cee-water/cjgleason/ted/swot-ml/data/multigraph_manual/datalakes/training')
# datalake.optimize(0)

In [5]:
import xarray as xr

sub_counts = subs_df['outlet_id'].value_counts().to_dict()
subs_df = subs_df.sort_values(by='outlet_id', key = lambda x: x.map(sub_counts), ascending=False)

BATCH_SIZE = 1000
batches = []
for basin_id, basin_group in subs_df.groupby('outlet_id'):
    basin_subs = basin_subbasin_dict[basin_id]x
    n_subs = len(basin_subs)

    for i in range(0, n_subs, BATCH_SIZE):
        batch_subs = basin_subs[i : i + BATCH_SIZE]
        batches.append((basin_id, batch_subs))

def get_batch_era5_df(basin_id, batch_subs):
    root = save_dir / f"datalakes/training/dynamic_data/era5/basin={basin_id}"

    dfs = []
    for d in root.iterdir():
        tmp_df = pd.concat([pd.read_parquet(f) for f in d.glob("*.parquet")])
        tmp_df = tmp_df.set_index(['subbasin','date'])
        tmp_df = tmp_df.loc[pd.IndexSlice[batch_subs, :], :]
        dfs.append(tmp_df)
    
    df = pd.concat(dfs)
    df = df.loc[~df.index.duplicated(keep='first'), :]
    return df

processed_basins = set()
failed_basins = {}
for basin_id, batch_subs in tqdm(batches):
    basin_path = store.store_path / basin_id 
    if (basin_path / 'ro_mean').is_dir():
        ds = xr.open_zarr(basin_path)
        nan_count = ds['ro_mean'].isnull().sum().compute().item()
        if nan_count == 0:
            continue
    
    basin_subs = basin_subbasin_dict[basin_id]
    batch_df_list = []

    try:
        batch_df = get_batch_era5_df(basin_id, batch_subs)
        init_vars = basin_id not in processed_basins
        store.write_batch_data(basin_id, batch_df, basin_subs, batch_subs, init_vars)
        processed_basins.union({basin_id})
    except Exception as e: 
        failed_basins[basin_id] = e
        raise e

100%|██████████| 1508/1508 [44:29<00:00,  1.77s/it]

In [ ]:
266

In [6]:
batch_df

                                             ssrd_mean     strd_mean  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00  3.176756e+07  2.818138e+07
               2015-01-02 00:00:00+00:00  3.223902e+07  2.863344e+07
               2015-01-03 00:00:00+00:00  2.381179e+07  2.815478e+07
               2015-01-04 00:00:00+00:00  3.275706e+07  2.696731e+07
               2015-01-05 00:00:00+00:00  3.288375e+07  2.992960e+07
...                                                ...           ...
ABOM-102984010 2025-12-27 00:00:00+00:00  1.834709e+07  2.877304e+07
               2025-12-28 00:00:00+00:00  3.235656e+07  2.654268e+07
               2025-12-29 00:00:00+00:00  3.310289e+07  2.744607e+07
               2025-12-30 00:00:00+00:00  3.296509e+07  2.709251e+07
               2025-12-31 00:00:00+00:00  3.309605e+07  2.732326e+07

                                               ro_mean      sro_mean  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00  1.503372e-08  0.000000e+00
               2015-01-02 00:00:00+00:00  1.722280e-08  0.000000e+00
               2015-01-03 00:00:00+00:00  2.980232e-08  0.000000e+00
               2015-01-04 00:00:00+00:00  2.980232e-08  0.000000e+00
               2015-01-05 00:00:00+00:00  2.246098e-08  0.000000e+00
...                                                ...           ...
ABOM-102984010 2025-12-27 00:00:00+00:00  2.607327e-06  4.193518e-08
               2025-12-28 00:00:00+00:00  2.535080e-06  0.000000e+00
               2025-12-29 00:00:00+00:00  2.517255e-06  0.000000e+00
               2025-12-30 00:00:00+00:00  2.469628e-06  0.000000e+00
               2025-12-31 00:00:00+00:00  2.456665e-06  2.285194e-09

                                            e_mean       tp_mean  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00 -0.000341  1.290134e-06
               2015-01-02 00:00:00+00:00 -0.000444  2.145250e-06
               2015-01-03 00:00:00+00:00 -0.000251  1.299381e-06
               2015-01-04 00:00:00+00:00 -0.000308  2.990087e-06
               2015-01-05 00:00:00+00:00 -0.000424  8.574305e-07
...                                            ...           ...
ABOM-102984010 2025-12-27 00:00:00+00:00 -0.000977  2.342487e-05
               2025-12-28 00:00:00+00:00 -0.001240  2.131183e-06
               2025-12-29 00:00:00+00:00 -0.001236  1.284480e-06
               2025-12-30 00:00:00+00:00 -0.001250  8.523463e-07
               2025-12-31 00:00:00+00:00 -0.001217  2.137012e-06

                                               sp_mean    d2m_mean  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00  97239.430646  281.680918
               2015-01-02 00:00:00+00:00  97409.321352  282.850554
               2015-01-03 00:00:00+00:00  97787.337662  278.965451
               2015-01-04 00:00:00+00:00  97599.654488  282.527995
               2015-01-05 00:00:00+00:00  97239.071113  282.829329
...                                                ...         ...
ABOM-102984010 2025-12-27 00:00:00+00:00  98453.178023  278.708177
               2025-12-28 00:00:00+00:00  98552.394148  281.244677
               2025-12-29 00:00:00+00:00  98813.668509  280.405255
               2025-12-30 00:00:00+00:00  98675.470554  280.409691
               2025-12-31 00:00:00+00:00  98134.370378  279.553260

                                            t2m_mean  fal_mean      ssrd_var  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00  295.512250  0.210996  2.469542e+10
               2015-01-02 00:00:00+00:00  292.707864  0.211212  1.562200e+09
               2015-01-03 00:00:00+00:00  292.915523  0.211428  6.677691e+10
               2015-01-04 00:00:00+00:00  297.830483  0.211643  7.819740e+08
               2015-01-05 00:00:00+00:00  304.165377  0.211857  8.962799e+08
...                                              ...       ...           ...
ABOM-102984010 2025-12-27 00:00:00+00:00  291.973022  0.128101  3.201891e+11
               2025-12-28 00:00:00+00:00  293.120645  0.128214  3.506433e+10
               2025-12-29 00:00:00+00:00  292.970336  0.128318  9.196975e+08
               2025-12-30 00:00:00+00:00  294.096833  0.128425  2.201324e+09
               2025-12-31 00:00:00+00:00  297.306937  0.128528  1.485531e+09

                                              strd_var        ro_var  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00  1.799716e+09  1.957723e-18
               2015-01-02 00:00:00+00:00  3.232642e+09  2.920514e-17
               2015-01-03 00:00:00+00:00  1.788747e+09  0.000000e+00
               2015-01-04 00:00:00+00:00  8.058702e+08  0.000000e+00
               2015-01-05 00:00:00+00:00  4.000873e+09  5.549922e-17
...                                                ...           ...
ABOM-102984010 2025-12-27 00:00:00+00:00  7.881161e+09  8.787917e-12
               2025-12-28 00:00:00+00:00  1.863314e+09  8.506929e-12
               2025-12-29 00:00:00+00:00  7.483794e+08  8.303547e-12
               2025-12-30 00:00:00+00:00  8.721402e+08  8.102778e-12
               2025-12-31 00:00:00+00:00  2.213844e+09  7.869503e-12

                                               sro_var         e_var  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00  0.000000e+00  6.118708e-10
               2015-01-02 00:00:00+00:00  0.000000e+00  9.458811e-10
               2015-01-03 00:00:00+00:00  0.000000e+00  3.823843e-10
               2015-01-04 00:00:00+00:00  0.000000e+00  5.398174e-10
               2015-01-05 00:00:00+00:00  0.000000e+00  8.961612e-10
...                                                ...           ...
ABOM-102984010 2025-12-27 00:00:00+00:00  3.358746e-17  2.556810e-07
               2025-12-28 00:00:00+00:00  0.000000e+00  2.096293e-07
               2025-12-29 00:00:00+00:00  0.000000e+00  1.834142e-07
               2025-12-30 00:00:00+00:00  0.000000e+00  2.655485e-07
               2025-12-31 00:00:00+00:00  1.180391e-17  2.092613e-07

                                                tp_var        sp_var  \
subbasin       date
56155034       2015-01-01 00:00:00+00:00  8.428385e-16  29437.293014
               2015-01-02 00:00:00+00:00  0.000000e+00  29740.604188
               2015-01-03 00:00:00+00:00  4.484155e-44  28728.931209
               2015-01-04 00:00:00+00:00  0.000000e+00  27549.533455
               2015-01-05 00:00:00+00:00  1.121039e-44  23890.032261
...                                                ...           ...
ABOM-102984010 2025-12-27 00:00:00+00:00  2.592835e-11  18198.201452
               2025-12-28 00:00:00+00:00  1.793662e-43  18737.429892
               2025-12-29 00:00:00+00:00  4.484155e-44  18843.170241
               2025-12-30 00:00:00+00:00  1.121039e-44  17810.260731
               2025-12-31 00:00:00+00:00  1.793662e-43  16950.126513

                                           d2m_var   t2m_var   fal_var
subbasin       date
56155034       2015-01-01 00:00:00+00:00  0.023632  0.003100  0.000021
               2015-01-02 00:00:00+00:00  0.016823  0.003264  0.000022
               2015-01-03 00:00:00+00:00  0.003344  0.013964  0.000022
               2015-01-04 00:00:00+00:00  0.007748  0.008076  0.000022
               2015-01-05 00:00:00+00:00  0.173475  0.052372  0.000022
...                                            ...       ...       ...
ABOM-102984010 2025-12-27 00:00:00+00:00  0.020942  0.008638  0.000179
               2025-12-28 00:00:00+00:00  0.034425  0.013311  0.000179
               2025-12-29 00:00:00+00:00  0.007066  0.012389  0.000179
               2025-12-30 00:00:00+00:00  0.016663  0.015954  0.000178
               2025-12-31 00:00:00+00:00  0.072385  0.013419  0.000178

[336040 rows x 20 columns]

In [52]:

tmp = pd.read_parquet('/nas/cee-water/cjgleason/ted/swot-ml/data/multigraph_manual/datalakes/training/dynamic_data/era5/basin=USGS-14246900/year=1983/part-00002-9369e52c-7378-429b-88c6-ddb97b5dbc96-c000.zstd.parquet')

tmp

,date,ssrd_mean,strd_mean,ro_mean,sro_mean,e_mean,tp_mean,sp_mean,d2m_mean,t2m_mean,...,strd_var,ro_var,sro_var,e_var,tp_var,sp_var,d2m_var,t2m_var,fal_var,subbasin
0,1983-12-31 00:00:00+00:00,5.164583e+06,2.400597e+07,0.000008,8.082325e-06,-0.000167,0.005205,100143.602950,265.285063,266.475176,...,1.957817e+10,4.397316e-12,2.883222e-12,1.434406e-09,2.415832e-07,6.508864e+05,0.346675,0.391446,1.359393e-03,78017400
1,1983-12-31 00:00:00+00:00,5.520677e+06,2.509972e+07,0.000029,1.563233e-05,-0.000101,0.008436,96955.163018,270.627767,272.537437,...,3.860369e+10,3.617793e-10,5.334791e-11,7.052063e-10,1.269360e-07,5.611102e+05,0.181795,0.195899,5.905695e-06,78017445
2,1983-12-31 00:00:00+00:00,5.479941e+06,2.473411e+07,0.000022,1.469519e-05,-0.000143,0.007062,97254.040425,269.444913,270.921102,...,3.067791e+10,1.255174e-10,9.433805e-12,1.376925e-09,2.390943e-07,6.646891e+05,0.422507,0.666880,1.465186e-04,78017945
3,1983-12-31 00:00:00+00:00,4.964483e+06,2.570039e+07,0.000139,8.482945e-05,-0.000047,0.009384,96602.703082,271.919168,273.313719,...,8.649024e+09,3.428317e-10,8.126469e-11,1.427461e-10,1.661545e-07,8.817612e+05,0.010186,0.019848,1.477066e-07,USGS-14015000
4,1983-12-31 00:00:00+00:00,5.628195e+06,2.469006e+07,0.000045,1.092153e-05,-0.000096,0.007688,97485.255375,269.550946,271.172536,...,6.287276e+10,2.790962e-10,3.328955e-11,7.368626e-10,5.766100e-08,5.530347e+05,0.383774,0.731503,5.345863e-05,78017442
5,1983-12-31 00:00:00+00:00,5.105030e+06,2.545666e+07,0.000085,5.891747e-05,-0.000087,0.008340,98382.766058,271.537618,272.834428,...,9.881400e+09,5.888247e-10,1.356858e-10,4.031517e-10,1.691273e-07,1.578291e+05,0.044417,0.061047,4.463079e-06,USGS-14015350
6,1983-12-31 00:00:00+00:00,5.113936e+06,2.405339e+07,0.000082,1.026970e-06,-0.000096,0.003950,96422.876651,269.800787,270.530155,...,8.108241e+10,3.011797e-09,1.287740e-12,1.229453e-09,7.306089e-08,5.829162e+06,1.060154,0.863114,9.334200e-04,78017618
7,1983-12-31 00:00:00+00:00,5.195957e+06,2.373036e+07,0.000008,6.776523e-06,-0.000158,0.003316,98365.302834,265.505926,266.545378,...,8.919912e+09,3.647940e-12,1.092894e-12,9.681225e-10,3.503883e-08,3.332937e+05,2.699607,2.249719,7.626489e-04,78020026
8,1983-12-31 00:00:00+00:00,5.110880e+06,2.396591e+07,0.000006,6.238745e-06,-0.000304,0.003482,99374.581412,267.747477,268.635864,...,8.721581e+09,1.496859e-12,1.519885e-12,4.844037e-08,4.017751e-08,1.629034e+06,2.104439,2.309446,4.213032e-03,78019699
9,1983-12-31 00:00:00+00:00,5.172596e+06,2.375831e+07,0.000005,4.504469e-06,-0.000134,0.004162,99856.591976,264.320887,265.353746,...,1.619937e+10,3.086450e-12,3.061086e-12,1.647948e-10,6.775354e-08,1.744837e+06,0.401196,0.356935,1.058512e-04,78017403
10,1983-12-31 00:00:00+00:00,5.153260e+06,2.346745e+07,0.000008,4.323698e-07,-0.000119,0.003465,97816.273837,263.610633,265.170249,...,5.289087e+09,5.370083e-11,9.545832e-13,1.512984e-09,1.254212e-08,1.617153e+06,0.311719,0.553588,8.891440e-05,78018229
11,1983-12-31 00:00:00+00:00,5.114802e+06,2.320308e+07,0.000103,3.098718e-08,-0.000056,0.003685,98117.365814,263.271637,264.398555,...,7.189011e+09,9.385195e-10,1.525128e-15,1.886584e-10,8.559859e-09,2.618630e+06,0.057590,0.049209,5.856576e-05,78018063
12,1983-12-31 00:00:00+00:00,5.220050e+06,2.353980e+07,0.000006,2.816078e-06,-0.000156,0.003349,97890.279337,263.862205,265.438007,...,1.196011e+10,3.277735e-11,6.448181e-12,2.018909e-09,2.049281e-08,1.016685e+06,1.071880,1.722518,3.318366e-04,78017611
13,1983-12-31 00:00:00+00:00,5.486476e+06,2.414711e+07,0.000022,1.264518e-05,-0.000256,0.003354,99228.330366,270.067538,271.498389,...,2.371163e+10,2.111278e-10,1.729267e-11,1.660485e-08,9.934271e-08,2.000246e+06,0.463859,0.889880,2.188534e-03,78019694
14,1983-12-31 00:00:00+00:00,5.066178e+06,2.325030e+07,0.000110,8.235646e-09,-0.000046,0.003839,96027.809309,263.065004,264.131077,...,3.280665e+09,1.321132e-09,4.923205e-16,8.501039e-11,2.698324e-08,1.084077e+06,0.022215,0.022238,4.750121e-05,78018109
15,1983-12-31 00:00:00+00:00,5.281634e+06,2.410225e+07,0.000008,7.551001e-06,-0.000402,0.003421,100080.037900,269.703302,270.987087,...,2.155078e+10,2.299181e-11,6.226642e-12,6.305236e-08,1.615627e-07,7.822569e+05,0.358432,0.882081,7.140946e-03,78019697
16,1983-12-31 00:00:00+00:00,5.206229e+06,2.387860e+07,0.000051,4.513922e-06,-0.000155,0.003472,97007.800111,268.104832,269.354287,...,2.829252e+10,2.451665e-09,4.277843e-12,2.311031e-09,1.814835e-08,4.212704e+06,1.038369,0.493503,7.450129e-04,78017615
17,1983-12-31 00:00:00+00:00,5.281217e+06,2.386263e+07,0.000026,9.325752e-06,-0.000149,0.003113,97703.878575,268.316457,269.393302,...,8.948709e+09,6.933234e-10,3.021299e-12,1.114357e-08,2.370911e-08,1.991312e+06,0.937462,0.616457,1.333904e-03,78020003
18,1983-12-31 00:00:00+00:00,5.228447e+06,2.345661e+07,0.000016,1.183089e-06,-0.000120,0.003539,97860.841405,263.037725,264.279143,...,5.832168e+09,4.894624e-10,1.613428e-12,7.033321e-10,4.755776e-09,4.582393e+05,0.035106,0.023052,4.257716e-05,USGS-12510500
19,1983-12-31 00:00:00+00:00,5.211299e+06,2.351435e+07,0.000023,2.325750e-06,-0.000114,0.003711,99515.445440,263.569813,264.673254,...,2.200699e+10,6.757387e-10,5.585889e-12,5.907135e-10,1.050606e-08,9.270517e+05,0.044926,0.029561,8.422684e-05,78017605
20,1983-12-31 00:00:00+00:00,5.127933e+06,2.347724e+07,0.000033,8.684151e-07,-0.000098,0.003699,97650.788563,264.585512,266.043499,...,2.126836e+10,9.718147e-10,4.483957e-12,3.404341e-09,1.232853e-07,2.208723e+06,1.831373,2.316826,9.197421e-04,USGS-12508990

In [53]:
len(tmp['subbasin'].unique())

21

In [45]:
basin_id

'USGS-14246900'

In [44]:
len(batch_subs)

1000

In [41]:
len(tmp_df.index.get_level_values('subbasin').unique())

21

In [42]:
len(dfs[0].index.get_level_values('subbasin').unique())

1000

In [35]:
root = save_dir / f"datalakes/training/dynamic_data/era5/basin={basin_id}"
    
dfs = []
for f in root.glob("*/*.parquet"):
    tmp_df = pd.read_parquet(f).set_index(['subbasin','date'])
    # tmp_df = tmp_df.loc[pd.IndexSlice[batch_subs, :], :]
    dfs.append(tmp_df)
df = pd.concat(dfs)

df

KeyError: '78027647'

In [32]:
failed_basins

{'USGS-14246900': "'78027647'"}

In [6]:
basin_subs = basin_subbasin_dict[basin_id]
batch_df_list = []

In [11]:
import xarray as xr
basin_path = store.store_path / basin_id
ds = xr.open_zarr(basin_path)

ds

<xarray.Dataset> Size: 61MB
Dimensions:         (date: 16437, subbasin: 20)
Coordinates:
  * date            (date) datetime64[ns] 131kB 1980-01-01 ... 2024-12-31
  * subbasin        (subbasin) <U14 1kB '56155034' ... 'ABOM-102984010'
Data variables: (12/23)
    d2m_mean        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    d2m_var         (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    discharge       (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    e_mean          (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    e_var           (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    fal_mean        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    ...              ...
    strd_var        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    t2m_mean        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    t2m_var         (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    tp_mean         (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    tp_var          (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    unit_discharge  (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
Attributes:
    normalization_stats:  {'d2m_mean': {'count': 328740, 'sum': 92463169.5251...

In [24]:
ds['ro_mean'].isnull().sum().compute().item()