In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
from tqdm import tqdm

save_dir = Path("/nas/cee-water/cjgleason/ted/swot-ml/data/multigraph_manual")
metadata_dir = save_dir / "metadata"

gauges = gpd.read_parquet(metadata_dir / "gauges.parquet").set_index('site_id')

subs_df = pd.read_parquet(metadata_dir / 'subbasins.parquet', columns=['site_id', 'is_gauge', 'uparea_km2', 'outlet_id'])
subs_df.index = subs_df.index.astype(str)

basin_subbasin_dict = subs_df.groupby('outlet_id').apply(lambda g: g.index.tolist(), include_groups=False).to_dict()

In [2]:
from data import ZarrBasinStore
store_path = Path("/scratch4/workspace/tlanghorst_umass_edu-swot-ml-zarr/zbs_batched")
store = ZarrBasinStore(store_path)

In [3]:
from data import BasinDataLake

datalake = BasinDataLake('/nas/cee-water/cjgleason/ted/swot-ml/data/multigraph_manual/datalakes/training')
datalake.optimize(0)

Compacting processing metadata...
	Metadata: Reduced file count by 0 (n_added=0, n_removed=0).
Compacting and ordering gauge data...
	gauge: Reduced file count by 0 (n_added=79940, n_removed=79940).
Compacting and ordering glow-s data...
	glow-s: Reduced file count by 0 (n_added=4358, n_removed=4358).
Compacting and ordering era5 data...
	era5: Reduced file count by 0 (n_added=66961, n_removed=66961).
Compacting and ordering swot-river data...
	swot-river: Reduced file count by 0 (n_added=834, n_removed=834).
Vacuuming processing metadata...
WARNING: Overriding retention period check for immediate deletion.

In [12]:
datalake.vacuum(0)

Vacuuming processing metadata...
WARNING: Overriding retention period check for immediate deletion.
Vacuuming gauge data...
WARNING: Overriding retention period check for immediate deletion.
Vacuuming glow-s data...
WARNING: Overriding retention period check for immediate deletion.
Vacuuming era5 data...
WARNING: Overriding retention period check for immediate deletion.
Vacuuming swot-river data...
WARNING: Overriding retention period check for immediate deletion.

In [22]:
store.compute_and_store_stats()

Dask client started. Dashboard at: http://127.0.0.1:8787/status

Basins:  41%|████      | 598/1472 [00:28<00:39, 21.86it/s]/nas/cee-water/cjgleason/ted/swot-ml/.venv/lib/python3.11/site-packages/distributed/client.py:3371: UserWarning: Sending large graph of size 11.09 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
Basins: 100%|██████████| 1472/1472 [03:02<00:00,  8.07it/s]

In [7]:
pd.read_parquet('/nas/cee-water/cjgleason/ted/swot-ml/data/multigraph_manual/datalakes/training/dynamic_data/era5/basin=USGS-14246900/year=1983/part-00002-6f1b3a5e-1fdb-4914-8194-c054481902e1-c000.zstd.parquet')

,date,ssrd_mean,strd_mean,ro_mean,sro_mean,e_mean,tp_mean,sp_mean,d2m_mean,t2m_mean,...,strd_var,ro_var,sro_var,e_var,tp_var,sp_var,d2m_var,t2m_var,fal_var,subbasin
0,1983-12-31 00:00:00+00:00,4.156502e+06,2.251223e+07,0.000167,0.000000e+00,0.000018,0.006927,90332.062284,263.726291,265.746002,...,1.544609e+10,1.825314e-09,0.000000e+00,4.825362e-10,3.439096e-06,3.810033e+06,0.151626,0.135179,0.005086,78014097
1,1983-12-31 00:00:00+00:00,3.937020e+06,2.258198e+07,0.000156,1.824479e-07,-0.000003,0.008685,91196.929638,266.429282,267.734834,...,2.546214e+10,1.003688e-09,9.346470e-15,1.892190e-09,1.808887e-06,3.684134e+06,0.505123,0.398315,0.007413,78015654
2,1983-12-31 00:00:00+00:00,4.048668e+06,2.259251e+07,0.000176,0.000000e+00,0.000020,0.007161,92478.823521,264.943882,267.053214,...,6.763775e+09,4.839647e-10,0.000000e+00,8.520516e-11,7.614239e-07,1.648684e+06,0.684389,0.552427,0.001536,USGS-12449500
3,1983-12-31 00:00:00+00:00,3.612212e+06,2.340019e+07,0.000468,0.000000e+00,0.000085,0.014063,83838.036956,264.969929,266.642201,...,5.026253e+10,3.793344e-09,0.000000e+00,1.598313e-10,6.186211e-06,1.718095e+06,0.573409,0.317557,0.000126,USGS-12447383
4,1983-12-31 00:00:00+00:00,2.874327e+06,2.436037e+07,0.000697,3.611223e-08,0.000086,0.024078,85230.234961,266.760573,268.156947,...,1.816719e+11,2.344496e-08,1.717503e-15,2.232493e-10,4.694119e-06,1.935366e+06,1.759465,1.320372,0.000965,78014323
5,1983-12-31 00:00:00+00:00,3.892924e+06,2.293660e+07,0.000318,0.000000e+00,0.000069,0.009587,88047.725255,265.547940,267.202442,...,2.264245e+10,7.250503e-09,0.000000e+00,1.095683e-09,2.029862e-06,7.531600e+06,0.693499,0.423235,0.007682,USGS-12448500
6,1983-12-31 00:00:00+00:00,4.099334e+06,2.252962e+07,0.000184,2.900291e-08,0.000037,0.007909,89472.991994,264.084869,265.795546,...,2.331061e+10,6.353915e-09,4.155003e-15,6.232848e-10,4.691081e-06,8.176354e+06,0.261452,0.336813,0.014139,78014093
7,1983-12-31 00:00:00+00:00,2.857394e+06,2.356249e+07,0.000427,2.809999e-07,0.000085,0.018576,85683.651612,265.800798,267.205429,...,8.667907e+10,9.095647e-09,6.748481e-14,1.789657e-10,1.400780e-05,1.078626e+06,0.098023,0.100793,0.000594,78015750
8,1983-12-31 00:00:00+00:00,3.052340e+06,2.355512e+07,0.000576,3.995249e-07,0.000076,0.020660,86002.618284,266.022727,267.326969,...,5.305511e+10,4.046160e-09,5.193502e-14,5.711979e-11,9.300016e-06,1.149405e+06,1.014047,0.969342,0.000843,78014154
9,1983-12-31 00:00:00+00:00,2.653412e+06,2.436483e+07,0.000792,4.885269e-08,0.000086,0.026442,86204.908367,267.568797,268.852981,...,1.720631e+11,3.453421e-08,6.820242e-15,3.344323e-10,4.494175e-06,1.150656e+06,0.613801,0.427301,0.000523,USGS-12451000
10,1983-12-31 00:00:00+00:00,4.407578e+06,2.234940e+07,0.000124,1.014685e-08,0.000011,0.006252,92120.157755,265.503899,266.924886,...,2.987076e+09,1.543621e-10,2.024572e-16,5.978122e-11,5.320403e-07,6.196633e+05,0.363080,0.137335,0.004520,USGS-12449950
11,1983-12-31 00:00:00+00:00,3.882280e+06,2.276028e+07,0.000242,0.000000e+00,0.000043,0.009185,89954.496058,264.817988,266.694631,...,1.504400e+10,4.856309e-09,0.000000e+00,3.254728e-10,1.457965e-06,8.258410e+06,0.564518,0.723016,0.006775,USGS-12448998
12,1983-12-31 00:00:00+00:00,4.841926e+06,2.567991e+07,0.000155,9.304547e-05,-0.000123,0.009435,96346.932944,271.810372,273.325723,...,6.032058e+10,5.354124e-09,1.128173e-09,7.113071e-09,1.623827e-06,5.862018e+06,0.261323,0.440535,0.007664,78017634
13,1983-12-31 00:00:00+00:00,5.369359e+06,2.522907e+07,0.000043,2.696170e-05,-0.000090,0.008254,96270.592207,270.854130,272.467022,...,6.588864e+10,7.292455e-10,5.514131e-11,2.603309e-09,1.090464e-06,6.473172e+05,0.377781,0.455567,0.000042,78017992
14,1983-12-31 00:00:00+00:00,5.410294e+06,2.431808e+07,0.000022,1.145941e-05,-0.000156,0.006267,98836.927893,267.490209,268.681271,...,2.498863e+10,1.474597e-10,7.726274e-13,1.673057e-09,1.206883e-07,3.640734e+05,0.694716,0.764613,0.000590,78017435
15,1983-12-31 00:00:00+00:00,5.673636e+06,2.424881e+07,0.000049,7.120901e-06,-0.000080,0.006789,98282.244068,268.057115,269.179791,...,2.323030e+10,1.089531e-10,8.738579e-12,1.964345e-10,1.158315e-07,9.831098e+04,0.283212,0.427012,0.000018,78017440
16,1983-12-31 00:00:00+00:00,5.128864e+06,2.551270e+07,0.000091,5.709133e-05,-0.000081,0.008669,96535.218135,271.656077,273.149817,...,7.069700e+10,3.120088e-09,6.386496e-10,1.937047e-09,1.165744e-06,3.968413e+06,0.355789,0.485828,0.004847,78018096
17,1983-12-31 00:00:00+00:00,5.137057e+06,2.563226e+07,0.000105,5.816461e-05,-0.000063,0.009291,94915.212262,271.996291,273.686905,...,6.731567e+10,3.275002e-09,4.931129e-10,2.400156e-09,1.034803e-06,4.165383e+06,0.366000,0.435252,0.010229,78018055
18,1983-12-31 00:00:00+00:00,5.719835e+06,2.455714e+07,0.000038,2.712528e-06,-0.000052,0.008238,97599.597135,269.127405,270.720983,...,2.392850e+10,4.980871e-10,1.481372e-11,6.455406e-10,1.043340e-07,2.178661e+05,0.196326,0.348729,0.000266,78017444
19,1983-12-31 00:00:00+00:00,5.203189e+06,2.496419e+07,0.000028,2.406296e-05,-0.000180,0.006818,98717.681133,269.872445,271.286552,...,4.890469e+10,3.987082e-10,1.597320e-10,1.781639e-09,3.343741e-07,2.097167e+05,0.746794,0.696554,0.000506,USGS-14018500
20,1983-12-31 00:00:00+00:00,5.568687e+06,2.382160e+07,0.000015,7.122491e-06,-0.000092,0.005652,99117.175620,265.855758,266.883181,...,2.058620e+10,5.660856e-11,6.128570e-12,8.197548e-10,1.553166e-07,1.202586e+05,0.578532,0.525198,0.000135,78018068

In [20]:
root = save_dir / f"datalakes/training/dynamic_data/era5/basin={basin_id}"

dfs = []
for d in root.iterdir():
    tmp_df = pd.concat([pd.read_parquet(f) for f in d.glob("*.parquet")])
    tmp_df = tmp_df.set_index(['subbasin','date'])
    tmp_df = tmp_df.loc[pd.IndexSlice[batch_subs, :], :]
    dfs.append(tmp_df)

df = pd.concat(dfs)
df = df.loc[~df.index.duplicated(keep='first'), :]


df

                                       ssrd_mean     strd_mean   ro_mean  \
subbasin date
78027647 2018-01-01 00:00:00+00:00  8.849740e+06  1.792424e+07  0.000015
         2018-01-02 00:00:00+00:00  8.580425e+06  1.955509e+07  0.000018
         2018-01-03 00:00:00+00:00  8.836628e+06  1.885518e+07  0.000017
         2018-01-04 00:00:00+00:00  8.494152e+06  1.973240e+07  0.000019
         2018-01-05 00:00:00+00:00  7.337224e+06  2.083619e+07  0.000018
...                                          ...           ...       ...
78022135 1998-12-27 00:00:00+00:00  2.535913e+06  2.831301e+07  0.003095
         1998-12-28 00:00:00+00:00  4.094774e+05  2.869260e+07  0.008158
         1998-12-29 00:00:00+00:00  4.003723e+05  3.053644e+07  0.036553
         1998-12-30 00:00:00+00:00  2.148224e+06  3.013492e+07  0.010608
         1998-12-31 00:00:00+00:00  5.767131e+06  2.920998e+07  0.009370

                                    sro_mean    e_mean       tp_mean  \
subbasin date
78027647 2018-01-01 00:00:00+00:00  0.000003 -0.000289  4.927687e-06
         2018-01-02 00:00:00+00:00  0.000006 -0.000368  4.261732e-07
         2018-01-03 00:00:00+00:00  0.000005 -0.000334  8.523463e-07
         2018-01-04 00:00:00+00:00  0.000007 -0.000332  4.410744e-07
         2018-01-05 00:00:00+00:00  0.000006 -0.000315  1.275539e-06
...                                      ...       ...           ...
78022135 1998-12-27 00:00:00+00:00  0.000222 -0.000405  5.876798e-03
         1998-12-28 00:00:00+00:00  0.003003 -0.000609  2.702943e-02
         1998-12-29 00:00:00+00:00  0.022920 -0.001141  7.244821e-02
         1998-12-30 00:00:00+00:00  0.000624 -0.001193  8.950118e-03
         1998-12-31 00:00:00+00:00  0.000092 -0.000854  3.571300e-03

                                         sp_mean    d2m_mean    t2m_mean  \
subbasin date
78027647 2018-01-01 00:00:00+00:00  87562.788993  264.967565  271.126935
         2018-01-02 00:00:00+00:00  87967.113794  266.843364  272.041725
         2018-01-03 00:00:00+00:00  87772.674112  266.303681  271.579381
         2018-01-04 00:00:00+00:00  87335.066199  267.105287  272.642031
         2018-01-05 00:00:00+00:00  87325.357601  269.657114  274.434404
...                                          ...         ...         ...
78022135 1998-12-27 00:00:00+00:00  98893.322172  277.816936  278.200085
         1998-12-28 00:00:00+00:00  98467.368021  282.038225  282.249459
         1998-12-29 00:00:00+00:00  99317.171567  280.709084  281.586540
         1998-12-30 00:00:00+00:00  99210.539198  280.871032  282.035264
         1998-12-31 00:00:00+00:00  98439.658452  281.387667  281.991250

                                    fal_mean      ssrd_var      strd_var  \
subbasin date
78027647 2018-01-01 00:00:00+00:00  0.269232  9.531285e+09  2.925480e+09
         2018-01-02 00:00:00+00:00  0.249196  9.840610e+09  1.286183e+09
         2018-01-03 00:00:00+00:00  0.232537  8.778969e+09  2.988906e+09
         2018-01-04 00:00:00+00:00  0.213380  6.871678e+09  4.163641e+09
         2018-01-05 00:00:00+00:00  0.196459  1.317666e+10  1.313480e+09
...                                      ...           ...           ...
78022135 1998-12-27 00:00:00+00:00  0.137655  5.844198e+08  5.279757e+09
         1998-12-28 00:00:00+00:00  0.134345  5.392968e+08  9.854799e+09
         1998-12-29 00:00:00+00:00  0.133963  3.532031e+08  1.766882e+10
         1998-12-30 00:00:00+00:00  0.134055  6.566406e+10  3.651336e+10
         1998-12-31 00:00:00+00:00  0.134181  4.801492e+10  2.300981e+10

                                          ro_var       sro_var         e_var  \
subbasin date
78027647 2018-01-01 00:00:00+00:00  4.800122e-11  5.499776e-14  9.705486e-10
         2018-01-02 00:00:00+00:00  5.821541e-11  9.209182e-13  1.474997e-09
         2018-01-03 00:00:00+00:00  5.889161e-11  1.000243e-12  1.386307e-09
         2018-01-04 00:00:00+00:00  6.607061e-11  2.223737e-12  1.486974e-09
         2018-01-05 00:00:00+00:00  6.258505e-11  1.576302e-12  8.970636e-10
...                                          ...           ...           ...
78022135 1998-12-27 00:00:00+00:00  3.491892e-07  6.777786e-09  4.200586e-08
         1998-12-28 00:00:00+00:00  1.037849e-06  1.466704e-07  8.977960e-08
         1998-12-29 00:00:00+00:00  1.425599e-05  1.311476e-05  2.599776e-07
         1998-12-30 00:00:00+00:00  5.334659e-06  4.548987e-08  1.177962e-07
         1998-12-31 00:00:00+00:00  2.976034e-06  1.588386e-09  2.325444e-08

                                          tp_var         sp_var   d2m_var  \
subbasin date
78027647 2018-01-01 00:00:00+00:00  6.547655e-12  654225.366005  0.020729
         2018-01-02 00:00:00+00:00  2.802597e-45  655739.285509  0.091582
         2018-01-03 00:00:00+00:00  1.121039e-44  662115.927405  0.024285
         2018-01-04 00:00:00+00:00  2.802597e-45  649486.348414  0.193350
         2018-01-05 00:00:00+00:00  4.484155e-44  632580.250728  0.157798
...                                          ...            ...       ...
78022135 1998-12-27 00:00:00+00:00  1.561186e-06  681107.721866  0.139877
         1998-12-28 00:00:00+00:00  2.487869e-06  636940.179615  0.173000
         1998-12-29 00:00:00+00:00  1.884806e-05  661557.463473  0.207619
         1998-12-30 00:00:00+00:00  1.811776e-06  670956.263966  0.165248
         1998-12-31 00:00:00+00:00  1.020498e-06  665403.871143  0.086879

                                     t2m_var   fal_var
subbasin date
78027647 2018-01-01 00:00:00+00:00  0.104896  0.000541
         2018-01-02 00:00:00+00:00  0.015324  0.000464
         2018-01-03 00:00:00+00:00  0.073063  0.000397
         2018-01-04 00:00:00+00:00  0.006209  0.000313
         2018-01-05 00:00:00+00:00  0.002648  0.000257
...                                      ...       ...
78022135 1998-12-27 00:00:00+00:00  0.205648  0.000322
         1998-12-28 00:00:00+00:00  0.245773  0.000354
         1998-12-29 00:00:00+00:00  0.218556  0.000367
         1998-12-30 00:00:00+00:00  0.274428  0.000369
         1998-12-31 00:00:00+00:00  0.163430  0.000371

[16437000 rows x 20 columns]

In [21]:
import xarray as xr

sub_counts = subs_df['outlet_id'].value_counts().to_dict()
subs_df = subs_df.sort_values(by='outlet_id', key = lambda x: x.map(sub_counts), ascending=False)

BATCH_SIZE = 1000
batches = []
for basin_id, basin_group in subs_df.groupby('outlet_id'):
    basin_subs = basin_subbasin_dict[basin_id]
    n_subs = len(basin_subs)

    for i in range(0, n_subs, BATCH_SIZE):
        batch_subs = basin_subs[i : i + BATCH_SIZE]
        batches.append((basin_id, batch_subs))

def get_batch_era5_df(basin_id, batch_subs):
    root = save_dir / f"datalakes/training/dynamic_data/era5/basin={basin_id}"

    dfs = []
    for d in root.iterdir():
        tmp_df = pd.concat([pd.read_parquet(f) for f in d.glob("*.parquet")])
        tmp_df = tmp_df.set_index(['subbasin','date'])
        tmp_df = tmp_df.loc[pd.IndexSlice[batch_subs, :], :]
        dfs.append(tmp_df)
        
    # dfs = []
    # for f in root.glob("*/*.parquet"):
    #     tmp_df = pd.read_parquet(f).set_index(['subbasin','date'])
    #     tmp_df = tmp_df.loc[pd.IndexSlice[batch_subs, :], :]
    #     dfs.append(tmp_df)
    
    df = pd.concat(dfs)
    df = df.loc[~df.index.duplicated(keep='first'), :]
    return df

processed_basins = set()
failed_basins = {}
for basin_id, batch_subs in tqdm(batches):
    basin_path = store.store_path / basin_id 
    if (basin_path / 'ro_mean').is_dir():
        ds = xr.open_zarr(basin_path)
        nan_count = ds['ro_mean'].isnull().sum().compute().item()
        if nan_count == 0:
            continue
    
    basin_subs = basin_subbasin_dict[basin_id]
    batch_df_list = []

    try:
        batch_df = get_batch_era5_df(basin_id, batch_subs)
    
        init_vars = basin_id not in processed_basins
        store.write_batch_data(basin_id, batch_df, basin_subs, batch_subs, init_vars)
        processed_basins.union({basin_id})
    except Exception as e: 
        failed_basins[basin_id] = e
        raise e

100%|██████████| 1508/1508 [06:28<00:00,  3.88it/s]

In [52]:
tmp = pd.read_parquet('/nas/cee-water/cjgleason/ted/swot-ml/data/multigraph_manual/datalakes/training/dynamic_data/era5/basin=USGS-14246900/year=1983/part-00002-9369e52c-7378-429b-88c6-ddb97b5dbc96-c000.zstd.parquet')

tmp

,date,ssrd_mean,strd_mean,ro_mean,sro_mean,e_mean,tp_mean,sp_mean,d2m_mean,t2m_mean,...,strd_var,ro_var,sro_var,e_var,tp_var,sp_var,d2m_var,t2m_var,fal_var,subbasin
0,1983-12-31 00:00:00+00:00,5.164583e+06,2.400597e+07,0.000008,8.082325e-06,-0.000167,0.005205,100143.602950,265.285063,266.475176,...,1.957817e+10,4.397316e-12,2.883222e-12,1.434406e-09,2.415832e-07,6.508864e+05,0.346675,0.391446,1.359393e-03,78017400
1,1983-12-31 00:00:00+00:00,5.520677e+06,2.509972e+07,0.000029,1.563233e-05,-0.000101,0.008436,96955.163018,270.627767,272.537437,...,3.860369e+10,3.617793e-10,5.334791e-11,7.052063e-10,1.269360e-07,5.611102e+05,0.181795,0.195899,5.905695e-06,78017445
2,1983-12-31 00:00:00+00:00,5.479941e+06,2.473411e+07,0.000022,1.469519e-05,-0.000143,0.007062,97254.040425,269.444913,270.921102,...,3.067791e+10,1.255174e-10,9.433805e-12,1.376925e-09,2.390943e-07,6.646891e+05,0.422507,0.666880,1.465186e-04,78017945
3,1983-12-31 00:00:00+00:00,4.964483e+06,2.570039e+07,0.000139,8.482945e-05,-0.000047,0.009384,96602.703082,271.919168,273.313719,...,8.649024e+09,3.428317e-10,8.126469e-11,1.427461e-10,1.661545e-07,8.817612e+05,0.010186,0.019848,1.477066e-07,USGS-14015000
4,1983-12-31 00:00:00+00:00,5.628195e+06,2.469006e+07,0.000045,1.092153e-05,-0.000096,0.007688,97485.255375,269.550946,271.172536,...,6.287276e+10,2.790962e-10,3.328955e-11,7.368626e-10,5.766100e-08,5.530347e+05,0.383774,0.731503,5.345863e-05,78017442
5,1983-12-31 00:00:00+00:00,5.105030e+06,2.545666e+07,0.000085,5.891747e-05,-0.000087,0.008340,98382.766058,271.537618,272.834428,...,9.881400e+09,5.888247e-10,1.356858e-10,4.031517e-10,1.691273e-07,1.578291e+05,0.044417,0.061047,4.463079e-06,USGS-14015350
6,1983-12-31 00:00:00+00:00,5.113936e+06,2.405339e+07,0.000082,1.026970e-06,-0.000096,0.003950,96422.876651,269.800787,270.530155,...,8.108241e+10,3.011797e-09,1.287740e-12,1.229453e-09,7.306089e-08,5.829162e+06,1.060154,0.863114,9.334200e-04,78017618
7,1983-12-31 00:00:00+00:00,5.195957e+06,2.373036e+07,0.000008,6.776523e-06,-0.000158,0.003316,98365.302834,265.505926,266.545378,...,8.919912e+09,3.647940e-12,1.092894e-12,9.681225e-10,3.503883e-08,3.332937e+05,2.699607,2.249719,7.626489e-04,78020026
8,1983-12-31 00:00:00+00:00,5.110880e+06,2.396591e+07,0.000006,6.238745e-06,-0.000304,0.003482,99374.581412,267.747477,268.635864,...,8.721581e+09,1.496859e-12,1.519885e-12,4.844037e-08,4.017751e-08,1.629034e+06,2.104439,2.309446,4.213032e-03,78019699
9,1983-12-31 00:00:00+00:00,5.172596e+06,2.375831e+07,0.000005,4.504469e-06,-0.000134,0.004162,99856.591976,264.320887,265.353746,...,1.619937e+10,3.086450e-12,3.061086e-12,1.647948e-10,6.775354e-08,1.744837e+06,0.401196,0.356935,1.058512e-04,78017403
10,1983-12-31 00:00:00+00:00,5.153260e+06,2.346745e+07,0.000008,4.323698e-07,-0.000119,0.003465,97816.273837,263.610633,265.170249,...,5.289087e+09,5.370083e-11,9.545832e-13,1.512984e-09,1.254212e-08,1.617153e+06,0.311719,0.553588,8.891440e-05,78018229
11,1983-12-31 00:00:00+00:00,5.114802e+06,2.320308e+07,0.000103,3.098718e-08,-0.000056,0.003685,98117.365814,263.271637,264.398555,...,7.189011e+09,9.385195e-10,1.525128e-15,1.886584e-10,8.559859e-09,2.618630e+06,0.057590,0.049209,5.856576e-05,78018063
12,1983-12-31 00:00:00+00:00,5.220050e+06,2.353980e+07,0.000006,2.816078e-06,-0.000156,0.003349,97890.279337,263.862205,265.438007,...,1.196011e+10,3.277735e-11,6.448181e-12,2.018909e-09,2.049281e-08,1.016685e+06,1.071880,1.722518,3.318366e-04,78017611
13,1983-12-31 00:00:00+00:00,5.486476e+06,2.414711e+07,0.000022,1.264518e-05,-0.000256,0.003354,99228.330366,270.067538,271.498389,...,2.371163e+10,2.111278e-10,1.729267e-11,1.660485e-08,9.934271e-08,2.000246e+06,0.463859,0.889880,2.188534e-03,78019694
14,1983-12-31 00:00:00+00:00,5.066178e+06,2.325030e+07,0.000110,8.235646e-09,-0.000046,0.003839,96027.809309,263.065004,264.131077,...,3.280665e+09,1.321132e-09,4.923205e-16,8.501039e-11,2.698324e-08,1.084077e+06,0.022215,0.022238,4.750121e-05,78018109
15,1983-12-31 00:00:00+00:00,5.281634e+06,2.410225e+07,0.000008,7.551001e-06,-0.000402,0.003421,100080.037900,269.703302,270.987087,...,2.155078e+10,2.299181e-11,6.226642e-12,6.305236e-08,1.615627e-07,7.822569e+05,0.358432,0.882081,7.140946e-03,78019697
16,1983-12-31 00:00:00+00:00,5.206229e+06,2.387860e+07,0.000051,4.513922e-06,-0.000155,0.003472,97007.800111,268.104832,269.354287,...,2.829252e+10,2.451665e-09,4.277843e-12,2.311031e-09,1.814835e-08,4.212704e+06,1.038369,0.493503,7.450129e-04,78017615
17,1983-12-31 00:00:00+00:00,5.281217e+06,2.386263e+07,0.000026,9.325752e-06,-0.000149,0.003113,97703.878575,268.316457,269.393302,...,8.948709e+09,6.933234e-10,3.021299e-12,1.114357e-08,2.370911e-08,1.991312e+06,0.937462,0.616457,1.333904e-03,78020003
18,1983-12-31 00:00:00+00:00,5.228447e+06,2.345661e+07,0.000016,1.183089e-06,-0.000120,0.003539,97860.841405,263.037725,264.279143,...,5.832168e+09,4.894624e-10,1.613428e-12,7.033321e-10,4.755776e-09,4.582393e+05,0.035106,0.023052,4.257716e-05,USGS-12510500
19,1983-12-31 00:00:00+00:00,5.211299e+06,2.351435e+07,0.000023,2.325750e-06,-0.000114,0.003711,99515.445440,263.569813,264.673254,...,2.200699e+10,6.757387e-10,5.585889e-12,5.907135e-10,1.050606e-08,9.270517e+05,0.044926,0.029561,8.422684e-05,78017605
20,1983-12-31 00:00:00+00:00,5.127933e+06,2.347724e+07,0.000033,8.684151e-07,-0.000098,0.003699,97650.788563,264.585512,266.043499,...,2.126836e+10,9.718147e-10,4.483957e-12,3.404341e-09,1.232853e-07,2.208723e+06,1.831373,2.316826,9.197421e-04,USGS-12508990

In [53]:
len(tmp['subbasin'].unique())

21

In [45]:
basin_id

'USGS-14246900'

In [44]:
len(batch_subs)

1000

In [41]:
len(tmp_df.index.get_level_values('subbasin').unique())

21

In [42]:
len(dfs[0].index.get_level_values('subbasin').unique())

1000

In [35]:
root = save_dir / f"datalakes/training/dynamic_data/era5/basin={basin_id}"
    
dfs = []
for f in root.glob("*/*.parquet"):
    tmp_df = pd.read_parquet(f).set_index(['subbasin','date'])
    # tmp_df = tmp_df.loc[pd.IndexSlice[batch_subs, :], :]
    dfs.append(tmp_df)
df = pd.concat(dfs)

df

KeyError: '78027647'

In [32]:
failed_basins

{'USGS-14246900': "'78027647'"}

In [6]:
basin_subs = basin_subbasin_dict[basin_id]
batch_df_list = []

In [11]:
import xarray as xr
basin_path = store.store_path / basin_id
ds = xr.open_zarr(basin_path)

ds

<xarray.Dataset> Size: 61MB
Dimensions:         (date: 16437, subbasin: 20)
Coordinates:
  * date            (date) datetime64[ns] 131kB 1980-01-01 ... 2024-12-31
  * subbasin        (subbasin) <U14 1kB '56155034' ... 'ABOM-102984010'
Data variables: (12/23)
    d2m_mean        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    d2m_var         (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    discharge       (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    e_mean          (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    e_var           (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    fal_mean        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    ...              ...
    strd_var        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    t2m_mean        (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    t2m_var         (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    tp_mean         (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    tp_var          (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
    unit_discharge  (date, subbasin) float64 3MB dask.array<chunksize=(365, 20), meta=np.ndarray>
Attributes:
    normalization_stats:  {'d2m_mean': {'count': 328740, 'sum': 92463169.5251...

In [24]:
ds['ro_mean'].isnull().sum().compute().item()